{
 "title": "internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Download",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "MB",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second/1000000"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "MB",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second/1000000"
    }
   ]
  },
  {
   "title": "speedtest ping",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "speedtest",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second",
     "legendFormat": "download"
    },
    {
     "expr": "speedtest_upload_bits_per_second",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Is alive?",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{humanname}}" }
   ]
  },
  {
   "title": "http duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (humanname)",
     "legendFormat": "{{humanname}}"
    }
   ]
  }
 ]
}